// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXQZWPkx8P7so7-14fXMLmdgATkkyCqfA',
    appId: '1:1000909588857:web:40709309d0782fe0c907a8',
    messagingSenderId: '1000909588857',
    projectId: 'redditclone-2b7f1',
    authDomain: 'redditclone-2b7f1.firebaseapp.com',
    storageBucket: 'redditclone-2b7f1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9BNJMrwXvFucHG3d55L-4fusyxUHdNKw',
    appId: '1:1000909588857:android:e9f393a92c3abaf1c907a8',
    messagingSenderId: '1000909588857',
    projectId: 'redditclone-2b7f1',
    storageBucket: 'redditclone-2b7f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqyUBaZBtSEm3aoe7gg_UpgCuecISMm_k',
    appId: '1:1000909588857:ios:e51cd92ea827e916c907a8',
    messagingSenderId: '1000909588857',
    projectId: 'redditclone-2b7f1',
    storageBucket: 'redditclone-2b7f1.appspot.com',
    iosBundleId: 'com.example.redditclone',
  );
}
